<optsExtract> ::= R_YEAR 
<timeStamp> ::= R_TIMESTAMP STRING 
<extract> ::= R_EXTRACT S_PARIZQ <optsExtract> R_FROM <timeStamp> S_PARDER 
<datatype> ::= <extract> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmt> 
<dateSource> ::= R_INTERVAL STRING 
<datePart> ::= R_DATE_PART S_PARIZQ STRING S_COMA <dateSource> S_PARDER 
<datatype> ::= <datePart> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<funcCall> ::= R_NOW S_PARIZQ S_PARDER 
<datatype> ::= <funcCall> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<optsExtract> ::= R_HOUR 
<timeStamp> ::= R_TIMESTAMP STRING 
<extract> ::= R_EXTRACT S_PARIZQ <optsExtract> R_FROM <timeStamp> S_PARDER 
<datatype> ::= <extract> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<optsExtract> ::= R_MINUTE 
<timeStamp> ::= R_TIMESTAMP STRING 
<extract> ::= R_EXTRACT S_PARIZQ <optsExtract> R_FROM <timeStamp> S_PARDER 
<datatype> ::= <extract> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<optsExtract> ::= R_SECOND 
<timeStamp> ::= R_TIMESTAMP STRING 
<extract> ::= R_EXTRACT S_PARIZQ <optsExtract> R_FROM <timeStamp> S_PARDER 
<datatype> ::= <extract> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<optsExtract> ::= R_YEAR 
<timeStamp> ::= R_TIMESTAMP STRING 
<extract> ::= R_EXTRACT S_PARIZQ <optsExtract> R_FROM <timeStamp> S_PARDER 
<datatype> ::= <extract> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<optsExtract> ::= R_MONTH 
<timeStamp> ::= R_TIMESTAMP STRING 
<extract> ::= R_EXTRACT S_PARIZQ <optsExtract> R_FROM <timeStamp> S_PARDER 
<datatype> ::= <extract> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<optsExtract> ::= R_DAY 
<timeStamp> ::= R_TIMESTAMP STRING 
<extract> ::= R_EXTRACT S_PARIZQ <optsExtract> R_FROM <timeStamp> S_PARDER 
<datatype> ::= <extract> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<dateSource> ::= R_INTERVAL STRING 
<datePart> ::= R_DATE_PART S_PARIZQ STRING S_COMA <dateSource> S_PARDER 
<datatype> ::= <datePart> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<dateSource> ::= R_INTERVAL STRING 
<datePart> ::= R_DATE_PART S_PARIZQ STRING S_COMA <dateSource> S_PARDER 
<datatype> ::= <datePart> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<current> ::= R_CURRENT_DATE 
<datatype> ::= <current> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<current> ::= R_CURRENT_TIME 
<datatype> ::= <current> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<timeStamp> ::= R_TIMESTAMP STRING 
<current> ::= <timeStamp> 
<datatype> ::= <current> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<init> ::= <stmtList> 
